#!/bin/bash

DIR=`readlink -e $1 |sed s/"\/$"//`

echo "# generated by ./config_mirage.bash"
echo "# used in kernel/Makefile.app for unikernel build dependencies"
echo
echo "CFG_MIRAGE_APP_DIR=$DIR"
echo "CFG_MIRAGE_APP_FILES=\\"

for f in $DIR/*.ml; do
    echo "$f \\"
done
echo

# note: most (if not all) of this should disappear with the new
#       functoria-enabled mirage

# specifics for mirage-www app
if [[ "`echo $DIR|grep -o mirage-www` " == "mirage-www " ]]; then
    echo "export MODE=solo5"
    echo "export FS=crunch"
    echo "export NET=direct"
    echo "export DHCP="
fi

