# generated by ./config_mirage.bash
# used in kernel/Makefile.app for unikernel build dependencies

CFG_MIRAGE_APP_DIR=/home/solo5/solo5-mirage/mirage-skeleton/console
CFG_MIRAGE_APP_FILES=\
/home/solo5/solo5-mirage/mirage-skeleton/console/config.ml \
/home/solo5/solo5-mirage/mirage-skeleton/console/unikernel.ml \

CFG_MIRAGE_APP_LIBS=\
	  -L/home/solo5/.opam/4.01.0/lib/io-page -lio_page_xen_stubs \

