# generated by ./config_mirage.bash
# used in kernel/Makefile.app for unikernel build dependencies

CFG_MIRAGE_APP_DIR=/home/solo5/solo5-mirage/mirage-skeleton/console
CFG_MIRAGE_APP_FILES=\
/home/solo5/solo5-mirage/mirage-skeleton/console/config.ml \
/home/solo5/solo5-mirage/mirage-skeleton/console/key_gen.ml \
/home/solo5/solo5-mirage/mirage-skeleton/console/main.ml \
/home/solo5/solo5-mirage/mirage-skeleton/console/unikernel.ml \

CFG_MIRAGE_APP_LIBS=\
	  -L/home/solo5/.opam/4.02.3/lib/mirage  \
	  -L/home/solo5/.opam/4.02.3/lib/astring  \
	  -L/home/solo5/.opam/4.02.3/lib/ipaddr  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-console  \
	  -L/home/solo5/.opam/4.02.3/lib/cstruct  \
	  -L/home/solo5/.opam/4.02.3/lib/lwt  \
	  -L/home/solo5/.opam/4.02.3/lib/lwt  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-console  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-types  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-bootvar  \
	  -L/home/solo5/.opam/4.02.3/lib/re  \
	  -L/home/solo5/.opam/4.02.3/lib/re  \
	  -L/home/solo5/.opam/4.02.3/lib/re  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-solo5  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-clock-xen  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-types  \
	  -L/home/solo5/.opam/4.02.3/lib/shared-memory-ring  \
	  -L/home/solo5/.opam/4.02.3/lib/shared-memory-ring  \
	  -L/home/solo5/.opam/4.02.3/lib/shared-memory-ring  \
	  -L/home/solo5/.opam/4.02.3/lib/shared-memory-ring  \
	  -L/home/solo5/.opam/4.02.3/lib/xenstore  \
	  -L/home/solo5/.opam/4.02.3/lib/xenstore  \
	  -L/home/solo5/.opam/4.02.3/lib/xen-gnt  \
	  -L/home/solo5/.opam/4.02.3/lib/mirage-profile  \
	  -L/home/solo5/.opam/4.02.3/lib/cstruct  \
	  -L/home/solo5/.opam/4.02.3/lib/io-page -lio_page_xen_stubs \
	  -L/home/solo5/.opam/4.02.3/lib/xen-evtchn  \
	  -L/home/solo5/.opam/4.02.3/lib/cstruct  \
	  -L/home/solo5/.opam/4.02.3/lib/sexplib  \
	  -L/home/solo5/.opam/4.02.3/lib/ocplib-endian  \
	  -L/home/solo5/.opam/4.02.3/lib/ocplib-endian  \
	  -L/home/solo5/.opam/4.02.3/lib/ocaml  \
	  -L/home/solo5/.opam/4.02.3/lib/ocaml  \
	  -L/home/solo5/.opam/4.02.3/lib/lwt  \
	  -L/home/solo5/.opam/4.02.3/lib/bytes  \
	  -L/home/solo5/.opam/4.02.3/lib/functoria  \
	  -L/home/solo5/.opam/4.02.3/lib/fmt  \
	  -L/home/solo5/.opam/4.02.3/lib/cmdliner  \

