# Copyright (c) 2015-2020 Contributors as noted in the AUTHORS file
#
# This file is part of Solo5, a sandboxed execution environment.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

.PHONY: all
all:
all_TARGETS :=

.SUFFIXES:
$(V).SILENT:

LDS.hvt := $(TOPDIR)/bindings/hvt/solo5_hvt.lds
BINDINGS.hvt := $(TOPDIR)/bindings/hvt/solo5_hvt.o
LDS.spt := $(TOPDIR)/bindings/spt/solo5_spt.lds
BINDINGS.spt := $(TOPDIR)/bindings/spt/solo5_spt.o
LDS.virtio := $(TOPDIR)/bindings/virtio/solo5_virtio.lds
BINDINGS.virtio := $(TOPDIR)/bindings/virtio/solo5_virtio.o
LDS.muen := $(TOPDIR)/bindings/muen/solo5_muen.lds
BINDINGS.muen := $(TOPDIR)/bindings/muen/solo5_muen.o
LDS.genode := $(TOPDIR)/bindings/genode/genode_dyn.ld
BINDINGS.genode := $(TOPDIR)/bindings/genode/solo5.lib.so
LDS.xen := $(TOPDIR)/bindings/xen/solo5_xen.lds
BINDINGS.xen := $(TOPDIR)/bindings/xen/solo5_xen.o

ELFTOOL := $(TOPDIR)/elftool/solo5-elftool

# As a test is currently a single source file, we don't try to do any 
# dependency auto-generation here, and just hard-code all expected dependencies
# as pre-requisites below.

manifest.c: manifest.json ../../include/solo5/mft_abi.h $(ELFTOOL)
	@echo "ELFTOOL $<"
	$(ELFTOOL) gen-manifest $< $@

%.o: %.c ../../include/solo5/solo5.h
	@echo "CC $<"
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

%.hvt: %.o manifest.o $(LDS.hvt) $(BINDINGS.hvt)
	@echo "LD $@"
	$(LD) $(LDFLAGS) -T $(LDS.hvt) $(BINDINGS.hvt) $< manifest.o -o $@

%.spt: %.o manifest.o $(LDS.spt) $(BINDINGS.spt)
	@echo "LD $@"
	$(LD) $(LDFLAGS) -T $(LDS.spt) $(BINDINGS.spt) $< manifest.o -o $@

%.virtio: %.o manifest.o $(LDS.virtio) $(BINDINGS.virtio)
	@echo "LD $@"
	$(LD) $(LDFLAGS) -T $(LDS.virtio) $(BINDINGS.virtio) $< manifest.o -o $@

%.muen: %.o manifest.o $(LDS.muen) $(BINDINGS.muen)
	@echo "LD $@"
	$(LD) $(LDFLAGS) -T $(LDS.muen) $(BINDINGS.muen) $< manifest.o -o $@

%.genode.o: %.c ../../include/solo5/solo5.h
	@echo "GENODECC $<"
	$(CC) $(GENODE_APP_CFLAGS) $(CPPFLAGS) -c $< -o $@

%.genode: %.genode.o manifest.genode.o $(LDS.genode) $(BINDINGS.genode)
	@echo "LD $@"
	$(LD) $(GENODE_APP_LDFLAGS) -T $(LDS.genode) $(BINDINGS.genode) \
	    $< manifest.genode.o -o $@

%.xen: %.o manifest.o $(LDS.xen) $(BINDINGS.xen)
	@echo "LD $@"
	$(LD) $(LDFLAGS) -T $(LDS.xen) $(BINDINGS.xen) $< manifest.o -o $@

%.xl: %.xen
	@echo "XL $@"
	sed -e s/@@NAME@@/$(test_NAME)/ \
	    -e s/@@KERNEL@@/$(test_NAME).xen/ \
	    ../config.xl.in >$@

ifdef CONFIG_HVT
    all_TARGETS += $(test_NAME).hvt
endif

ifdef CONFIG_SPT
    all_TARGETS += $(test_NAME).spt
endif

ifdef CONFIG_VIRTIO
    all_TARGETS += $(test_NAME).virtio
endif

ifdef CONFIG_MUEN
    all_TARGETS += $(test_NAME).muen
endif

ifdef CONFIG_GENODE
    all_TARGETS += $(test_NAME).genode
endif

ifdef CONFIG_XEN
    all_TARGETS += $(test_NAME).xen $(test_NAME).xl
endif

.PRECIOUS: $(test_NAME).o $(test_NAME).genode.o manifest.o manifest.genode.o

all: $(all_TARGETS)

.PHONY: clean

clean:
	@echo "CLEAN $(test_NAME)"
	$(RM) $(test_NAME).o $(test_NAME).genode.o \
	    manifest.c manifest.o manifest.genode.o $(all_TARGETS)
