# Copyright (c) 2015-2018 Contributors as noted in the AUTHORS file
#
# This file is part of Solo5, a sandboxed execution environment.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

TOP?=../..
include $(TOP)/Makefile.common

.PHONY: vt
vt: $(VT_TARGETS)

.PHONY: virtio
virtio:	$(VIRTIO_TARGETS)

.PHONY: muen
muen: $(MUEN_TARGETS)

BINDINGS_DIR=$(TOP)/bindings
SOLO5_VT_SRC=$(TOP)/tenders/vt

CFLAGS+=-I$(BINDINGS_DIR)

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@
.PRECIOUS: %.o

ifeq ($(BUILD_VT), yes)
Makefile.solo5-vt: $(SOLO5_VT_SRC)/solo5-vt-configure
	$(SOLO5_VT_SRC)/solo5-vt-configure $(SOLO5_VT_SRC) $(VT_MODULES)

-include Makefile.solo5-vt

%.vt: %.o $(BINDINGS_DIR)/vt/solo5_vt.lds $(BINDINGS_DIR)/vt/solo5_vt.o
	$(LD) -T $(BINDINGS_DIR)/vt/solo5_vt.lds $(LDFLAGS) -o $@ $(BINDINGS_DIR)/vt/solo5_vt.o $< $(LDLIBS)

$(BINDINGS_DIR)/vt/solo5_vt.o: 
	$(MAKE) -C $(BINDINGS_DIR) vt
endif

ifeq ($(BUILD_MUEN), yes)
%.muen: %.o $(BINDINGS_DIR)/muen/solo5_muen.lds $(BINDINGS_DIR)/muen/solo5_muen.o
	$(LD) -T $(BINDINGS_DIR)/muen/solo5_muen.lds $(LDFLAGS) -o $@ $(BINDINGS_DIR)/muen/solo5_muen.o $< $(LDLIBS)

$(BINDINGS_DIR)/muen/solo5_muen.o:
	$(MAKE) -C $(BINDINGS_DIR) muen
endif

%.virtio: %.o $(BINDINGS_DIR)/virtio/solo5_virtio.lds $(BINDINGS_DIR)/virtio/solo5_virtio.o
	$(LD) -T $(BINDINGS_DIR)/virtio/solo5_virtio.lds $(LDFLAGS) -o $@ $(BINDINGS_DIR)/virtio/solo5_virtio.o $< $(LDLIBS)

$(BINDINGS_DIR)/virtio/solo5_virtio.o: 
	$(MAKE) -C $(BINDINGS_DIR) virtio

.PHONY: clean solo5-vt-clean
clean: solo5-vt-clean
	$(RM) *.o $(VT_TARGETS) Makefile.solo5-vt $(VIRTIO_TARGETS) $(MUEN_TARGETS)
